#!/bin/sh
set -e
if [ -n "$1" ]; then
    PARAL=$1
else
    PARAL=8
fi

rm -rf ./build/app
mkdir -p ./build/app

if [ ! -d logs ];then
mkdir logs
fi

cd build/app
cmake -DCMAKE_BUILD_TYPE=Debug -DX_OPTION_STATIC=true -Wno-dev ../../Hammer
make -j ${PARAL}
make test
make install
cd ../..